name = "Adams"
license = "MIT"
licenselink = "https://github.com/Tokinx/Adams/blob/master/LICENSE"
description = "A simple and clean Hugo theme, ported from WordPress Adams theme"
homepage = "https://biji.io"
tags = ["blog", "minimal", "clean", "responsive"]
features = ["responsive", "clean design", "dark mode", "sepia mode"]
min_version = "0.112.0"

[author]
  name = "Tokin"
  homepage = "https://biji.io"

[original]
  author = "Tokin"
  homepage = "https://biji.io"
  repo = "https://github.com/Tokinx/Adams"
